### PR TITLE
Add a psplot command to plot and compare stats from multiple runs of psrecord

### PR DESCRIPTION
**Pull request by saimn**
This allow to compare multiple runs of psrecord on one plot. I have added a new command since it is easier than playing with argparse's sub-parsers.
It takes a list of log files from psrecord, with options to plot only mem or cpu. I don't know what is the best for colors and linestyles to distinguish easily all the lines (suggestions are welcome ;)). Currently it uses mpl's color cycle, so mem and cpu for a file will have the same color (and linestyle).
I didn't modify the plot from `main.py`, it could probably use the same code, but I'm waiting for your feedback before going further ;-).

```
usage: psplot [-h] [-m] [-c] [-o OUTPUT] [files [files ...]]

Plot stats from psrecord

positional arguments:
  files                 List of files to plot

optional arguments:
  -h, --help            show this help message and exit
  -m, --mem             Show memory values
  -c, --cpu             Show cpu values
  -o OUTPUT, --output OUTPUT
                        Save the plot to a file
```

### CODE REVIEW

**Comment by astrofrog** [comment]
@saimn - sorry for never replying to this. In principle I like this, but I'm wondering if ``psrecord-compare`` might be a better command name, so that it's clearer that it's associated with ``psrecord``. Or it could potentially be a special mode of psrecord, e.g. ``psrecord --compare``. Could you rebase this and we can go through a round of comments?

**Comment by saimn** [comment]
@astrofrog - I had also forgotten this PR ! 😄  Ok for the rebase.

**Comment by saimn** [comment]
@astrofrog - I pushed the rebased branch with a few updates. About the command interface, I think I chose `psplot` because it can be useful also to plot one log file, so not only for comparison. There are also several options for the interface:
- a new command, 
- a specific option, `--compare` or whatever, but it will possibly conflict with the exiting options and make the interface more difficult to understand
- subcommands: `psrecord plot` for instance. This suppose that the existing `psrecord` command  is moved to a subcommand `psrecord run` or something. And then I think it is possible to specify a default subcommand, to keep the compatibility.

**Comment by astrofrog** [comment]
So... better late than never, am I right? ;)

I think my preferred option would be ``psrecord plot``, so a sub-command.

Is there a way we can re-use the existing plotting code so that if someone does ``psrecord plot activity.txt`` they get the same plot that ``psrecord`` would have generated originally? I know this also adds the ability to compare, but it would be good to make it so that plotting a single one is consistent.

**Comment by saimn** [comment]
@astrofrog - Ok ;), I will have a look.

**Comment by saimn** [comment]
Closing this, anyone interested feel free to reuse this code or not and make a new PR :)

**Pull request closed without merging**
